### ISSUE TITLE
Task Creation/Editing Modal Not Working

### ISSUE THREAD

**Issue by takeo** [sytone/obsidian-tasks-x#5]
## Expected Behavior
Create/edit task modal should work

## Current Behavior
![CleanShot 2022-06-01 at 22 07 27](https://user-images.githubusercontent.com/23/171556947-c8e4137e-ee83-49d5-8046-8dc4ce4339ef.gif)

Currently the modal opens,  but the date fields aren't parsing and the task can't be saved. The modal can only be dismissed by clicking the close icon or hitting escape.

## Steps to Reproduce
Open the modal using the command to create/edit a task. When creating a new task the form can be tabbed through, but the fields don't seem to be active. The date fields don't parse when typing, clicking the apply button doesn't do anything, hitting return does nothing.

![CleanShot 2022-06-01 at 22 10 47@2x](https://user-images.githubusercontent.com/23/171557214-0eb82685-b4ae-45fd-a538-63c912e4fdd6.png)

## Context (Environment)
* Obsidian version: 0.14.15
* Tasks version: 2.0.11
* [x] I have tried it with all other plugins disabled and the error still occurs

**Comment by sytone** [comment]
Thanks for the feedback. I’ll will look at it in the next day to work out the root cause. I have rewired the internals a bit.

**Comment by takeo** [comment]
Looks like the 2.0.12 update fixed this, thanks!

**Comment by sytone** [comment]
Apologies for the error you hit, I have been able to reproduce the issue and fixed the root cause. Release 2.0.12 has this fix in it and is now released for usage.

Please confirm that you no longer see the issue on your end and we can close up the issue. Thanks for providing this feedback with the level of detail as well. It is appreciated.
